// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lufibpvqicrxxvzwtepo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1ZmlicHZxaWNyeHh2end0ZXBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODY3OTAsImV4cCI6MjA2NDc2Mjc5MH0.ZUbZOPU0vyXnUPAizbVshdZpaQIIj45DpISd8tSmJ3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);